use actix_web::{test, web, App};
use orderbook::controller::controller::{
    get_open_orders, get_recent_trades, load_event_stream, LoadEventStreamResponse,
};
use rust_decimal::Decimal;
use serde_json::json;
use std::fs;
use std::io::Write;
use uuid::Uuid;

fn write_event_file(events: serde_json::Value) -> std::path::PathBuf {
    let path = std::env::temp_dir().join(format!("event-stream-{}.json", Uuid::new_v4()));
    let mut file = fs::File::create(&path).expect("unable to create event file");
    let payload = serde_json::to_string_pretty(&events).expect("serialize events");
    file.write_all(payload.as_bytes())
        .expect("write events to disk");
    path
}

#[actix_web::test]
async fn load_event_stream_applies_sequence() {
    let app = test::init_service(
        App::new()
            .route("/load_event_stream", web::post().to(load_event_stream))
            .route("/get_open_orders", web::get().to(get_open_orders))
            .route("/get_recent_trades", web::get().to(get_recent_trades)),
    )
    .await;

    let symbol = format!("EVT-{}", Uuid::new_v4().simple());

    let events = json!([
        {
            "type": "limit",
            "order_id": "evt-lim-1",
            "side": "BUY",
            "price": "100.00",
            "quantity": "5",
            "tif": "GTC"
        },
        {
            "type": "limit",
            "order_id": "evt-lim-2",
            "side": "SELL",
            "price": "101.00",
            "quantity": "3",
            "tif": "GTC"
        },
        {
            "type": "market",
            "side": "SELL",
            "quantity": "2",
            "tif": "IOC"
        },
        {
            "type": "cancel",
            "order_id": "evt-lim-2"
        }
    ]);

    let path = write_event_file(events);

    let load_req = test::TestRequest::post()
        .uri("/load_event_stream")
        .set_json(json!({
            "symbol": symbol,
            "path": path.to_string_lossy()
        }))
        .to_request();

    let load_resp = test::call_service(&app, load_req).await;
    assert!(load_resp.status().is_success());

    let payload: LoadEventStreamResponse = test::read_body_json(load_resp).await;
    assert_eq!(payload.applied_events, 4);
    assert_eq!(payload.rejected_events, 0);
    assert!(payload.errors.is_empty());
    assert!(!payload.simulation_id.is_empty());

    // Remaining resting order should be the partially filled BUY
    let open_req = test::TestRequest::get()
        .uri(&format!(
            "/get_open_orders?symbol={}&side=BUY",
            payload.symbol
        ))
        .to_request();
    let open_resp = test::call_service(&app, open_req).await;
    assert!(open_resp.status().is_success());
    let open_orders: Vec<orderbook::controller::controller::OrderDto> =
        test::read_body_json(open_resp).await;
    assert_eq!(open_orders.len(), 1);
    assert_eq!(open_orders[0].order_id, "evt-lim-1");
    assert_eq!(open_orders[0].remaining_quantity, Decimal::new(3, 0));

    // Ensure the trade generated by the market event is recorded
    let trades_req = test::TestRequest::get()
        .uri(&format!(
            "/get_recent_trades?symbol={}&limit=10",
            payload.symbol
        ))
        .to_request();
    let trades_resp = test::call_service(&app, trades_req).await;
    assert!(trades_resp.status().is_success());
    let trades: Vec<orderbook::controller::controller::TradeDto> =
        test::read_body_json(trades_resp).await;
    assert_eq!(trades.len(), 1);
    assert_eq!(trades[0].quantity, Decimal::new(2, 0));

    fs::remove_file(path).ok();
}

#[actix_web::test]
async fn load_event_stream_handles_missing_file() {
    let app = test::init_service(
        App::new().route("/load_event_stream", web::post().to(load_event_stream)),
    )
    .await;

    let load_req = test::TestRequest::post()
        .uri("/load_event_stream")
        .set_json(json!({
            "symbol": "MISSING",
            "path": "C:/not/a/real/file.json"
        }))
        .to_request();

    let load_resp = test::call_service(&app, load_req).await;
    assert_eq!(load_resp.status(), actix_web::http::StatusCode::BAD_REQUEST);
}
